2021-12-17 11:36:28,530 (5679/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-17 11:36:56,006 (5790/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-17 11:37:24,967 (5790/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at end of input\nLINE 1: show table\n                  ^\n')
2021-12-17 11:37:24,968 (5790/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: show table\n                  ^\n\n'
2021-12-17 11:37:28,533 (5790/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2021-12-17 11:37:28,533 (5790/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2021-12-19 13:15:15,071 (6221/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-19 13:15:53,032 (6221/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 581, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: fe_sendauth: no password supplied\n\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 590, in connect\n    pgexecute = PGExecute(\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 260, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 306, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/usr/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: FATAL:  password authentication failed for user "awsuser"\nFATAL:  password authentication failed for user "awsuser"\n\n'
2021-12-19 13:16:09,921 (6545/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-22 15:28:38,056 (2932/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-22 15:28:44,093 (2932/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 584, in connect\n    passwd = click.prompt(\n  File "/usr/lib/python3.10/site-packages/click/termui.py", line 168, in prompt\n    value = prompt_func(prompt)\n  File "/usr/lib/python3.10/site-packages/click/termui.py", line 150, in prompt_func\n    raise Abort() from None\nclick.exceptions.Abort\n'
2021-12-22 15:28:48,029 (2998/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-22 15:30:13,481 (2998/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at end of input\nLINE 1: show table\n                  ^\n')
2021-12-22 15:30:13,522 (2998/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: show table\n                  ^\n\n'
2021-12-22 15:42:00,304 (5190/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-22 15:49:33,716 (5823/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-23 11:45:11,357 (30072/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2021-12-23 15:29:12,759 (52025/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-02 23:28:29,631 (15355/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 12:44:46,438 (3655/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 12:45:08,537 (3746/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 12:46:22,236 (3923/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 12:47:25,042 (4154/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 12:49:27,050 (4824/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 12:49:34,646 (4989/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 13:07:45,217 (8898/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 13:09:09,215 (9095/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 13:09:14,351 (9150/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 13:12:32,633 (11819/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 13:12:32,633 (11819/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-06 13:13:31,104 (11987/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-06 13:13:31,104 (11987/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-06 13:14:15,652 (11987/MainThread) pgcli.main ERROR - sql: '\\dt;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-06 13:14:15,665 (11987/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
2022-01-06 13:14:23,899 (11987/MainThread) pgcli.pgexecute ERROR - sql: 'dt', error: SyntaxError('syntax error at or near "dt"\nLINE 1: dt\n        ^\n')
2022-01-06 13:14:23,911 (11987/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "dt"\nLINE 1: dt\n        ^\n\n'
2022-01-10 09:45:34,276 (5221/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-10 09:45:34,276 (5221/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-10 09:45:59,929 (5221/MainThread) pgcli.main ERROR - sql: 'describe demography;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-10 09:45:59,971 (5221/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
2022-01-10 09:46:06,453 (5221/MainThread) pgcli.main ERROR - sql: '\\dt;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-10 09:46:06,453 (5221/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
2022-01-10 09:46:51,862 (5221/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at end of input\nLINE 1: show table\n                  ^\n')
2022-01-10 09:46:51,875 (5221/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: show table\n                  ^\n\n'
2022-01-10 09:46:54,626 (5221/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2022-01-10 09:46:54,627 (5221/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2022-01-10 09:47:08,042 (5529/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-10 09:47:08,042 (5529/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-10 09:47:22,716 (5529/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"\n')
2022-01-10 09:47:22,717 (5529/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedObject: unrecognized configuration parameter "tables"\n\n'
2022-01-10 09:47:26,524 (5529/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at end of input\nLINE 1: show table\n                  ^\n')
2022-01-10 09:47:26,524 (5529/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: show table\n                  ^\n\n'
2022-01-10 09:47:31,838 (5529/MainThread) pgcli.pgexecute ERROR - sql: 'show TABLE', error: SyntaxError('syntax error at end of input\nLINE 1: show TABLE\n                  ^\n')
2022-01-10 09:47:31,839 (5529/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 1: show TABLE\n                  ^\n\n'
2022-01-10 09:47:57,907 (5529/MainThread) pgcli.pgexecute ERROR - sql: '\\l', error: UndefinedColumn('column d.datcollate does not exist\n')
2022-01-10 09:47:57,909 (5529/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 455, in run\n    response = pgspecial.execute(cur, sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/main.py", line 117, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/dbcommands.py", line 60, in list_databases\n    cur.execute(query)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column d.datcollate does not exist\n\n'
2022-01-10 09:48:06,972 (5529/MainThread) pgcli.pgexecute ERROR - sql: '\\list', error: UndefinedColumn('column d.datcollate does not exist\n')
2022-01-10 09:48:06,972 (5529/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 455, in run\n    response = pgspecial.execute(cur, sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/main.py", line 117, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/dbcommands.py", line 60, in list_databases\n    cur.execute(query)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column d.datcollate does not exist\n\n'
2022-01-10 09:48:10,096 (5529/MainThread) pgcli.pgexecute ERROR - sql: '\\list', error: UndefinedColumn('column d.datcollate does not exist\n')
2022-01-10 09:48:10,096 (5529/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 455, in run\n    response = pgspecial.execute(cur, sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/main.py", line 117, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/dbcommands.py", line 60, in list_databases\n    cur.execute(query)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column d.datcollate does not exist\n\n'
2022-01-10 09:48:29,406 (5529/MainThread) pgcli.main ERROR - sql: '\\d;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-10 09:48:29,407 (5529/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
2022-01-10 10:00:08,612 (9458/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-10 10:00:08,612 (9458/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-10 10:00:23,268 (9458/MainThread) pgcli.main ERROR - sql: '\\d;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-10 10:00:23,269 (9458/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
2022-01-10 12:34:19,015 (17661/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-10 12:34:19,016 (17661/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-10 12:34:29,833 (17661/MainThread) pgcli.main ERROR - sql: '\\d;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-10 12:34:29,876 (17661/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
2022-01-10 12:40:55,636 (18814/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-10 12:40:55,637 (18814/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-10 12:41:04,864 (18814/MainThread) pgcli.pgexecute ERROR - sql: 'l', error: SyntaxError('syntax error at or near "l"\nLINE 1: l\n        ^\n')
2022-01-10 12:41:04,865 (18814/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "l"\nLINE 1: l\n        ^\n\n'
2022-01-10 12:41:08,011 (18814/MainThread) pgcli.pgexecute ERROR - sql: '\\l', error: UndefinedColumn('column d.datcollate does not exist\n')
2022-01-10 12:41:08,012 (18814/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 455, in run\n    response = pgspecial.execute(cur, sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/main.py", line 117, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/dbcommands.py", line 60, in list_databases\n    cur.execute(query)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column d.datcollate does not exist\n\n'
2022-01-10 12:41:13,812 (18814/MainThread) pgcli.main ERROR - sql: 'select zipcode from demography limit 100;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-10 12:41:13,813 (18814/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
2022-01-10 12:47:10,992 (19886/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-10 12:47:10,992 (19886/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-10 12:47:22,756 (19886/MainThread) pgcli.pgexecute ERROR - sql: '/dt', error: SyntaxError('syntax error at or near "/"\nLINE 1: /dt\n        ^\n')
2022-01-10 12:47:22,757 (19886/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /dt\n        ^\n\n'
2022-01-10 12:52:20,635 (20890/MainThread) pgcli.main INFO - No default pager found in environment. Using os default pager
2022-01-10 12:52:20,636 (20890/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-01-10 12:52:29,802 (20890/MainThread) pgcli.pgexecute ERROR - sql: 'l', error: SyntaxError('syntax error at or near "l"\nLINE 1: l\n        ^\n')
2022-01-10 12:52:29,803 (20890/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 472, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 507, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "l"\nLINE 1: l\n        ^\n\n'
2022-01-10 12:52:32,240 (20890/MainThread) pgcli.pgexecute ERROR - sql: '\\l', error: UndefinedColumn('column d.datcollate does not exist\n')
2022-01-10 12:52:32,241 (20890/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 455, in run\n    response = pgspecial.execute(cur, sql)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/main.py", line 117, in execute\n    return special_cmd.handler(cur=cur, pattern=pattern, verbose=verbose)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgspecial/dbcommands.py", line 60, in list_databases\n    cur.execute(query)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/pgexecute.py", line 168, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column d.datcollate does not exist\n\n'
2022-01-10 12:52:36,104 (20890/MainThread) pgcli.main ERROR - sql: '\\dt;', error: AttributeError("'str' object has no attribute 'parent'")
2022-01-10 12:52:36,105 (20890/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 261, in format_unencoded\n    on, off = self.style_string[str(ttype)]\nKeyError: \'Token.Output.TableSeparator\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 668, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 939, in _evaluate_command\n    formatted = format_output(title, cur, headers, status, settings)\n  File "/home/vinny/.local/lib/python3.10/site-packages/pgcli/main.py", line 1483, in format_output\n    formatted = formatter.format_output(cur, headers, **output_kwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/output_formatter.py", line 168, in format_output\n    data, headers = f(data, headers, column_types=column_types, **fkwargs)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in style_output\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 170, in <genexpr>\n    newfmt = tabulate.TableFormat(*(addColorInElt(val) for val in srcfmt))\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 160, in addColorInElt\n    return tabulate.Line(\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 161, in <genexpr>\n    *(style_field(table_separator_token, val) for val in elt)\n  File "/home/vinny/.local/lib/python3.10/site-packages/cli_helpers/tabular_output/tabulate_adapter.py", line 153, in style_field\n    formatter.format(((token, field),), s)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 250, in format\n    return Formatter.format(self, tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatter.py", line 94, in format\n    return self.format_unencoded(tokensource, outfile)\n  File "/usr/lib/python3.10/site-packages/pygments/formatters/terminal256.py", line 282, in format_unencoded\n    ttype = ttype.parent\nAttributeError: \'str\' object has no attribute \'parent\'\n'
